// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.34014
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace test.Evolution2.AcceptanceTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class CampaignFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Campaign.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Campaign", "", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "Campaign")))
            {
                test.Evolution2.AcceptanceTests.Features.CampaignFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 3
#line 4
 testRunner.Given("I am logged into evolution with username \"yacosta1\" and password \"camry14\" and en" +
                    "vironment \"PROD\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Campaign Media Type Exists For Special Survey Live Calls")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Campaign")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("WebDriver", "Chrome")]
        public virtual void CampaignMediaTypeExistsForSpecialSurveyLiveCalls_With_Chrome()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Campaign Media Type Exists For Special Survey Live Calls", new string[] {
                        "Selenium"});
#line 8
this.ScenarioSetup(scenarioInfo);
 testRunner.Given("I am using the \"Chrome\" browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 3
this.FeatureBackground();
#line 9
 if (testRunner.ScenarioContext.ContainsKey("CurrentStep")) { testRunner.ScenarioContext["CurrentStep"] = "Given I have a list of campaign step ids for company \"3238\""; } else { testRunner.ScenarioContext.Add("CurrentStep", "Given I have a list of campaign step ids for company \"3238\""); }
            testRunner.Given("I have a list of campaign step ids for company \"3238\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
 if (testRunner.ScenarioContext.ContainsKey("CurrentStep")) { testRunner.ScenarioContext["CurrentStep"] = "When I navigate to the view campaign step media resource for each of them"; } else { testRunner.ScenarioContext.Add("CurrentStep", "When I navigate to the view campaign step media resource for each of them"); }
 testRunner.When("I navigate to the view campaign step media resource for each of them", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
 if (testRunner.ScenarioContext.ContainsKey("CurrentStep")) { testRunner.ScenarioContext["CurrentStep"] = "Then every id should return sample media not found"; } else { testRunner.ScenarioContext.Add("CurrentStep", "Then every id should return sample media not found"); }
#line 11
 testRunner.Then("every id should return sample media not found", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Campaign Media Type Exists For Special Survey Live Calls")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Campaign")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("WebDriver", "AndroidChrome")]
        public virtual void CampaignMediaTypeExistsForSpecialSurveyLiveCalls_With_AndroidChrome()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Campaign Media Type Exists For Special Survey Live Calls", new string[] {
                        "Selenium"});
#line 8
this.ScenarioSetup(scenarioInfo);
 testRunner.Given("I am using the \"AndroidChrome\" browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 3
this.FeatureBackground();
#line 9
 if (testRunner.ScenarioContext.ContainsKey("CurrentStep")) { testRunner.ScenarioContext["CurrentStep"] = "Given I have a list of campaign step ids for company \"3238\""; } else { testRunner.ScenarioContext.Add("CurrentStep", "Given I have a list of campaign step ids for company \"3238\""); }
            testRunner.Given("I have a list of campaign step ids for company \"3238\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
 if (testRunner.ScenarioContext.ContainsKey("CurrentStep")) { testRunner.ScenarioContext["CurrentStep"] = "When I navigate to the view campaign step media resource for each of them"; } else { testRunner.ScenarioContext.Add("CurrentStep", "When I navigate to the view campaign step media resource for each of them"); }
 testRunner.When("I navigate to the view campaign step media resource for each of them", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
 if (testRunner.ScenarioContext.ContainsKey("CurrentStep")) { testRunner.ScenarioContext["CurrentStep"] = "Then every id should return sample media not found"; } else { testRunner.ScenarioContext.Add("CurrentStep", "Then every id should return sample media not found"); }
#line 11
 testRunner.Then("every id should return sample media not found", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Campaign Media Type Exists For Special Survey Live Calls")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Campaign")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("WebDriver", "IE")]
        public virtual void CampaignMediaTypeExistsForSpecialSurveyLiveCalls_With_IE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Campaign Media Type Exists For Special Survey Live Calls", new string[] {
                        "Selenium"});
#line 8
this.ScenarioSetup(scenarioInfo);
 testRunner.Given("I am using the \"IE\" browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 3
this.FeatureBackground();
#line 9
 if (testRunner.ScenarioContext.ContainsKey("CurrentStep")) { testRunner.ScenarioContext["CurrentStep"] = "Given I have a list of campaign step ids for company \"3238\""; } else { testRunner.ScenarioContext.Add("CurrentStep", "Given I have a list of campaign step ids for company \"3238\""); }
            testRunner.Given("I have a list of campaign step ids for company \"3238\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
 if (testRunner.ScenarioContext.ContainsKey("CurrentStep")) { testRunner.ScenarioContext["CurrentStep"] = "When I navigate to the view campaign step media resource for each of them"; } else { testRunner.ScenarioContext.Add("CurrentStep", "When I navigate to the view campaign step media resource for each of them"); }
 testRunner.When("I navigate to the view campaign step media resource for each of them", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
 if (testRunner.ScenarioContext.ContainsKey("CurrentStep")) { testRunner.ScenarioContext["CurrentStep"] = "Then every id should return sample media not found"; } else { testRunner.ScenarioContext.Add("CurrentStep", "Then every id should return sample media not found"); }
#line 11
 testRunner.Then("every id should return sample media not found", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Campaign Media Type Exists For Special Survey Live Calls")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Campaign")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("WebDriver", "Firefox")]
        public virtual void CampaignMediaTypeExistsForSpecialSurveyLiveCalls_With_Firefox()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Campaign Media Type Exists For Special Survey Live Calls", new string[] {
                        "Selenium"});
#line 8
this.ScenarioSetup(scenarioInfo);
 testRunner.Given("I am using the \"Firefox\" browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 3
this.FeatureBackground();
#line 9
 if (testRunner.ScenarioContext.ContainsKey("CurrentStep")) { testRunner.ScenarioContext["CurrentStep"] = "Given I have a list of campaign step ids for company \"3238\""; } else { testRunner.ScenarioContext.Add("CurrentStep", "Given I have a list of campaign step ids for company \"3238\""); }
            testRunner.Given("I have a list of campaign step ids for company \"3238\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
 if (testRunner.ScenarioContext.ContainsKey("CurrentStep")) { testRunner.ScenarioContext["CurrentStep"] = "When I navigate to the view campaign step media resource for each of them"; } else { testRunner.ScenarioContext.Add("CurrentStep", "When I navigate to the view campaign step media resource for each of them"); }
 testRunner.When("I navigate to the view campaign step media resource for each of them", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
 if (testRunner.ScenarioContext.ContainsKey("CurrentStep")) { testRunner.ScenarioContext["CurrentStep"] = "Then every id should return sample media not found"; } else { testRunner.ScenarioContext.Add("CurrentStep", "Then every id should return sample media not found"); }
#line 11
 testRunner.Then("every id should return sample media not found", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
